"""
Protobuf bindings for Canopy Plugin Protocol
"""

from .account_pb2 import Account, Pool, Escrow  # type: ignore[attr-defined]
from .event_pb2 import Event, EventCustom  # type: ignore[attr-defined]
from .tx_pb2 import (
    Transaction,
    MessageSend,
    MessageCreateEscrow,
    MessageRelease,
    MessageRefund,
    FeeParams,
    Signature,
)  # type: ignore[attr-defined]

from .plugin_pb2 import (  # type: ignore[attr-defined]
    FSMToPlugin,
    PluginToFSM,
    PluginConfig,
    PluginFSMConfig,
    PluginGenesisRequest,
    PluginGenesisResponse,
    PluginBeginRequest,
    PluginBeginResponse,
    PluginCheckRequest,
    PluginCheckResponse,
    PluginDeliverRequest,
    PluginDeliverResponse,
    PluginEndRequest,
    PluginEndResponse,
    PluginError,
    PluginStateReadRequest,
    PluginStateReadResponse,
    PluginStateWriteRequest,
    PluginStateWriteResponse,
    PluginKeyRead,
    PluginRangeRead,
    PluginReadResult,
    PluginSetOp,
    PluginDeleteOp,
    PluginStateEntry,
)

__all__ = [
    "Account",
    "Pool",
    "Escrow",
    "Event",
    "EventCustom",
    "Transaction",
    "MessageSend",
    "MessageCreateEscrow",
    "MessageRelease",
    "MessageRefund",
    "FeeParams",
    "Signature",
    "FSMToPlugin",
    "PluginToFSM",
    "PluginConfig",
    "PluginFSMConfig",
    "PluginGenesisRequest",
    "PluginGenesisResponse",
    "PluginBeginRequest",
    "PluginBeginResponse",
    "PluginCheckRequest",
    "PluginCheckResponse",
    "PluginDeliverRequest",
    "PluginDeliverResponse",
    "PluginEndRequest",
    "PluginEndResponse",
    "PluginError",
    "PluginStateReadRequest",
    "PluginStateReadResponse",
    "PluginStateWriteRequest",
    "PluginStateWriteResponse",
    "PluginKeyRead",
    "PluginRangeRead",
    "PluginReadResult",
    "PluginSetOp",
    "PluginDeleteOp",
    "PluginStateEntry",
]
