# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x05types\"w\n\x07\x41\x63\x63ount\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12\x17\n\x0f\x65scrows_created\x18\x03 \x01(\x04\x12\x18\n\x10\x65scrows_released\x18\x04 \x01(\x04\x12\x18\n\x10\x65scrows_received\x18\x05 \x01(\x04\"\"\n\x04Pool\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\"\x98\x01\n\x06\x45scrow\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05\x62uyer\x18\x02 \x01(\x0c\x12\x0e\n\x06seller\x18\x03 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x04\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x16\n\x0etimeout_height\x18\x06 \x01(\x04\x12\x0e\n\x06status\x18\x07 \x01(\x04\x12\x16\n\x0e\x63reated_height\x18\x08 \x01(\x04\x42.Z,github.com/canopy-network/go-plugin/contractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/canopy-network/go-plugin/contract'
  _globals['_ACCOUNT']._serialized_start=24
  _globals['_ACCOUNT']._serialized_end=143
  _globals['_POOL']._serialized_start=145
  _globals['_POOL']._serialized_end=179
  _globals['_ESCROW']._serialized_start=182
  _globals['_ESCROW']._serialized_end=334
# @@protoc_insertion_point(module_scope)
