# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tx.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08tx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xd2\x01\n\x0bTransaction\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12!\n\x03msg\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12#\n\tsignature\x18\x03 \x01(\x0b\x32\x10.types.Signature\x12\x16\n\x0e\x63reated_height\x18\x04 \x01(\x04\x12\x0c\n\x04time\x18\x05 \x01(\x04\x12\x0b\n\x03\x66\x65\x65\x18\x06 \x01(\x04\x12\x0c\n\x04memo\x18\x07 \x01(\t\x12\x12\n\nnetwork_id\x18\x08 \x01(\x04\x12\x10\n\x08\x63hain_id\x18\t \x01(\x04\"G\n\x0bMessageSend\x12\x14\n\x0c\x66rom_address\x18\x01 \x01(\x0c\x12\x12\n\nto_address\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\"a\n\tFeeParams\x12\x10\n\x08send_fee\x18\x01 \x01(\x04\x12\x19\n\x11\x63reate_escrow_fee\x18\x02 \x01(\x04\x12\x13\n\x0brelease_fee\x18\x03 \x01(\x04\x12\x12\n\nrefund_fee\x18\x04 \x01(\x04\"q\n\x13MessageCreateEscrow\x12\r\n\x05\x62uyer\x18\x01 \x01(\x0c\x12\x0e\n\x06seller\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x16\n\x0etimeout_height\x18\x05 \x01(\x04\"2\n\x0eMessageRelease\x12\r\n\x05\x62uyer\x18\x01 \x01(\x0c\x12\x11\n\tescrow_id\x18\x02 \x01(\x04\"3\n\rMessageRefund\x12\x0f\n\x07\x63laimer\x18\x01 \x01(\x0c\x12\x11\n\tescrow_id\x18\x02 \x01(\x04\"2\n\tSignature\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"R\n\rMessageFaucet\x12\x16\n\x0esigner_address\x18\x01 \x01(\x0c\x12\x19\n\x11recipient_address\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x42.Z,github.com/canopy-network/go-plugin/contractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/canopy-network/go-plugin/contract'
  _globals['_TRANSACTION']._serialized_start=47
  _globals['_TRANSACTION']._serialized_end=257
  _globals['_MESSAGESEND']._serialized_start=259
  _globals['_MESSAGESEND']._serialized_end=330
  _globals['_FEEPARAMS']._serialized_start=332
  _globals['_FEEPARAMS']._serialized_end=429
  _globals['_MESSAGECREATEESCROW']._serialized_start=431
  _globals['_MESSAGECREATEESCROW']._serialized_end=544
  _globals['_MESSAGERELEASE']._serialized_start=546
  _globals['_MESSAGERELEASE']._serialized_end=596
  _globals['_MESSAGEREFUND']._serialized_start=598
  _globals['_MESSAGEREFUND']._serialized_end=649
  _globals['_SIGNATURE']._serialized_start=651
  _globals['_SIGNATURE']._serialized_end=701
  _globals['_MESSAGEFAUCET']._serialized_start=703
  _globals['_MESSAGEFAUCET']._serialized_end=785
# @@protoc_insertion_point(module_scope)
